### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by eix128** [linagora/james-project#3287]
Hi ,

1- )  i got dns error.As shown below log:

00:15:35.226 [ERROR] o.a.j.d.l.AbstractDomainList - Cannot get IP address(es) for Domain : localhost
00:15:35.441 [INFO ] o.a.j.m.m.MemoryMailRepositoryStore - JamesMailStore init... org.apache.james.mailrepository.memory.MemoryMailRepositoryStore@2ae4c424
00:15:35.588 [INFO ] r.r.Receiver - Consumer amq.ctag-qSLCTS_-sFmwWlMwp87bTQ consuming from eventbus-5ba4e99b-17f6-4ac0-bd91-b8e759abd809 has been registered
00:15:35.619 [INFO ] o.a.j.d.l.AbstractDomainList - Local host is: 172.17.0.7
00:15:35.702 [ERROR] o.a.j.d.l.AbstractDomainList - Cannot get IP address(es) for Domain : james.linagora.com
00:15:35.703 [WARN ] o.a.j.d.d.DNSJavaService - Error determining result 
java.lang.IllegalStateException: Lookup of localhost A isn't done
	at org.xbill.DNS.Lookup.checkDone(Lookup.java:594)
	at org.xbill.DNS.Lookup.getResult(Lookup.java:631)
	at org.apache.james.dnsservice.dnsjava.DNSJavaService.lookup(DNSJavaService.java:378)
	at org.apache.james.dnsservice.dnsjava.DNSJavaService.lookupNoException(DNSJavaService.java:400)
	at org.apache.james.dnsservice.dnsjava.DNSJavaService.getAllByName(DNSJavaService.java:473)
	at org.apache.james.domainlist.lib.AbstractDomainList.getDomainIpStream(AbstractDomainList.java:241)
	at org.apache.james.domainlist.lib.AbstractDomainList.lambda$getDomainsIpStream$2(AbstractDomainList.java:235)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.james.domainlist.lib.AbstractDomainList.detectIps(AbstractDomainList.java:204)
	at org.apache.james.domainlist.lib.AbstractDomainList.getDomainsWithType(AbstractDomainList.java:190)
	at org.apache.james.domainlist.lib.AbstractDomainList.getDomains(AbstractDomainList.java:169)
	at org.apache.james.domainlist.lib.AbstractDomainList.containsDomain(AbstractDomainList.java:164)
	at org.apache.james.mailetcontainer.impl.JamesMailetContext.configure(JamesMailetContext.java:428)
	at org.apache.james.modules.server.CamelMailetContainerModule.lambda$initMailetContext$2(CamelMailetContainerModule.java:136)
	at org.apache.james.utils.InitilizationOperationBuilder$PrivateImpl.initModule(InitilizationOperationBuilder.java:52)
	at com.github.fge.lambdas.consumers.ConsumerChainer.lambda$sneakyThrow$9(ConsumerChainer.java:73)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:439)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.james.utils.InitializationOperations.processConfigurables(InitializationOperations.java:53)
	at org.apache.james.utils.InitializationOperations.initModules(InitializationOperations.java:43)
	at org.apache.james.GuiceJamesServer.start(GuiceJamesServer.java:88)
	at org.apache.james.JamesServerMain.main(JamesServerMain.java:34)
	at org.apache.james.CassandraRabbitMQJamesServerMain.main(CassandraRabbitMQJamesServerMain.java:41)
00:15:35.703 [ERROR] o.a.j.d.l.AbstractDomainList - Cannot get IP address(es) for Domain : localhost
00:15:35.704 [WARN ] o.a.j.m.i.JamesMailetContext - The specified postmaster address ( postmaster@james.minet.net ) is not a local address.  This is not necessarily a problem, but it does mean that emails addressed to the postmaster will be routed to another server.  For some configurations this may cause problems.

2- ) And another problem , the mail server is not stable.
Some days later.It stops working.
Then i need to reinstall the server back.
Whats the problem ? is there any known issues?

3-) How to use SSL enabled with Thunderbird Linux ( Ubuntu ) .
is there any tutorial configuration for that? How to use with SSL

**Comment by chibenwa** [comment]
Hello @eix128 !

First thanks for using James and for your feedback.

1) Regarding the DNS error, do you really want James to auto-detect domains it should be using upon startup? You can disable this behaviour withing `domainlist.xml`. `james.linagora.com` is also likely not a domain you want to handle, and failed reverse DNS resolution for a non existing domain is not really surprising.

Please also change the postmaster address you rely on, `postmaster@james.minet.net ` is likely not the right one (mailetContainer.xml)

2) We run successfully James (upcoming) version 3.5.0 with no uptime problems. How did you installed James? Which version?

3) Configure imapserver.xml to allow IMAPS (SSL) on port 993. Then thunderbird configuration should be straightforward.

Hopes it helps.

Benoit
