### ISSUE TITLE
java.util.NoSuchElementException: heartbeatHandler

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3576]
```
 @timestamp 	
	July 6th 2020, 14:35:25.904
t _id 	
	LTkNI3MBwVD_OiFjbJjq

# _score 	
	 - 
t _type 	
	tester
t host 	
	james-69956575bc-jlsgx
t ip 	
	10.2.0.0
t logger 	
	org.apache.james.imapserver.netty.ImapChannelUpstreamHandler
t message 	
	Error while processing imap request
t protocol 	
	IMAP
t sessionId 	
	SID-rxzyjwusjzrc
t severity 	
	WARN
t stacktrace 	
	java.util.NoSuchElementException: heartbeatHandler
	at org.jboss.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:684)
	at org.jboss.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:153)
	at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.messageReceived(ImapChannelUpstreamHandler.java:215)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

```
 @timestamp 	
	July 6th 2020, 14:35:25.807
t _id 	
	KTkNI3MBwVD_OiFjbJjq

# _score 	
	 - 
t _type 	
	tester
t host 	
	james-69956575bc-jlsgx
t ip 	
	10.2.0.0
t logger 	
	org.apache.james.imapserver.netty.ImapChannelUpstreamHandler
t message 	
	Error while processing imap request
t protocol 	
	IMAP
t selectedMailbox 	
	1e54f590-49a4-11ea-b268-5bd54f0fe5f2
t sessionId 	
	SID-rxzyjwusjzrc
t severity 	
	WARN
t stacktrace 	
	java.lang.IllegalArgumentException: Duplicate handler name: heartbeatHandler
	at org.jboss.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:677)
	at org.jboss.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:117)
	at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.messageReceived(ImapChannelUpstreamHandler.java:192)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

`ImapChannelUpstreamHandler` can be called concurrently and several IMAP messages being processed parrallely on the same connection.

There is a data race: one command cannot add the heartbeat handler, the other one removes it.

org.jboss.netty.channel.ChannelPipeline is not concurrent friendly.

**DOD**
 - Write some concurrence integration tests for IMAP reproducing the issue
 - Fix it

**Comment by chibenwa** [comment]
Fixed
