### ISSUE TITLE
Please help me,Is this a bug?James(version 3.4) throw ClassCastException(SMTPTransport) when send mail.

### ISSUE THREAD

**Issue by panglei1984** [linagora/james-project#3650]
when send a mail,in the function MailDelivrerToHost.tryDeliveryToHost,the below code will throw ClassCastException:
transport = (SMTPTransport) session.getTransport(outgoingMailServer);

error stack is :
java.lang.ClassCastException: org.apache.geronimo.javamail.transport.smtp.SMTPTransport cannot be cast to com.sun.mail.smtp.SMTPTransport
	at org.apache.james.transport.mailets.remote.delivery.MailDelivrerToHost.tryDeliveryToHost(MailDelivrerToHost.java:66)
	at org.apache.james.transport.mailets.remote.delivery.MailDelivrer.doDeliver(MailDelivrer.java:126)
	at org.apache.james.transport.mailets.remote.delivery.MailDelivrer.tryDeliver(MailDelivrer.java:108)
	at org.apache.james.transport.mailets.remote.delivery.MailDelivrer.deliver(MailDelivrer.java:77)
	at org.apache.james.transport.mailets.remote.delivery.DeliveryRunnable.attemptDelivery(DeliveryRunnable.java:126)
	at org.apache.james.transport.mailets.remote.delivery.DeliveryRunnable.processMail(DeliveryRunnable.java:109)
	at org.apache.james.transport.mailets.remote.delivery.DeliveryRunnable.runStep(DeliveryRunnable.java:96)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:350)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

could you tell me how to resolve this problem?and why?
Thanks.

**Comment by Arsnael** [comment]
Hello @panglei1984 and thanks for the report !

James 3.4 is known to be a bit buggy... But the 3.5 version got released not long ago. Is it possible for you to try it and tell us if you still encounter the same problem with James 3.5?
