### ISSUE TITLE
Cannot find mailbox when moving a folder in a non-empty folder

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#370]
Have 
- a Folder "A"
- a folder "B" below "A"
- a folder "C" below "B"
- a folder "D"

Try to move the folder "D" below folder "A"

An error is launched in James

```
10:17:35.692 [WARN ] o.a.j.j.u.MailboxUtils - Cannot find mailbox for :D
org.apache.james.mailbox.exception.MailboxNotFoundException: null
    at org.apache.james.mailbox.cassandra.mail.CassandraMailboxMapper.findMailboxByPath(CassandraMailboxMapper.java:88)
    at org.apache.james.jmap.utils.MailboxUtils.getMailboxId(MailboxUtils.java:83)
    at org.apache.james.jmap.utils.MailboxUtils.mailboxFromMailboxPath(MailboxUtils.java:65)
    at org.apache.james.jmap.methods.GetMailboxesMethod.lambda$getMailboxesResponse$0(GetMailboxesMethod.java:94)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.apache.james.jmap.methods.GetMailboxesMethod.getMailboxesResponse(GetMailboxesMethod.java:99)
    at org.apache.james.jmap.methods.GetMailboxesMethod.process(GetMailboxesMethod.java:78)
    at org.apache.james.jmap.methods.RequestHandler.lambda$extractAndProcess$1(RequestHandler.java:67)
    at java.util.Optional.map(Optional.java:215)
    at org.apache.james.jmap.methods.RequestHandler.handle(RequestHandler.java:57)
    at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.apache.james.jmap.JMAPServlet.doPost(JMAPServlet.java:71)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
    at org.apache.james.jmap.FirstUserConnectionFilter.doFilter(FirstUserConnectionFilter.java:71)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
    at org.apache.james.jmap.AuthenticationFilter.doFilter(AuthenticationFilter.java:75)
    at org.apache.james.jmap.BypassAuthOnRequestMethod.tryAuth(BypassAuthOnRequestMethod.java:115)
    at org.apache.james.jmap.BypassAuthOnRequestMethod.doFilter(BypassAuthOnRequestMethod.java:97)
    at org.apache.james.jmap.AllowAllCrossOriginRequests.doFilter(AllowAllCrossOriginRequests.java:46)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
```

Here is the request payload 

> ﻿⁠⁠⁠⁠[["setMailboxes",{"update":{"48c1bde0-6aaa-11e6-adb7-2b97d605aec1":{"name":"D","parentId":"70f85900-6aa9-11e6-adb7-2b97d605aec1"}}},"#0"]]

**Comment by chibenwa** [comment]
I followed your steps, but I can not reproduce.

![screenshot from 2016-11-25 12-41-25](https://cloud.githubusercontent.com/assets/6928740/20615435/887c0800-b30c-11e6-8b20-f35f34600198.png)

Maybe rewriting JMAP without using mappers corrected the issue. Thanks, @rouazana ^^
