### ISSUE TITLE
IMAP Append: java.io.IOException: Stream Closed

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3757]
## Symptoms

In logs:

```
17:06:10.369 [ERROR] o.a.j.i.p.AppendProcessor - Unable to append message to mailbox #private:user2@james.org:INBOX.any
java.io.IOException: Stream Closed
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
	at com.google.common.io.ByteStreams$LimitedInputStream.read(ByteStreams.java:723)
	at org.apache.james.imap.utils.EolInputStream.read(EolInputStream.java:52)
	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:99)
	at org.apache.commons.io.input.TeeInputStream.read(TeeInputStream.java:129)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:136)
	at org.apache.james.util.io.BodyOffsetInputStream.read(BodyOffsetInputStream.java:45)
	at java.base/java.io.InputStream.read(InputStream.java:271)
	at org.apache.james.util.io.BodyOffsetInputStream.read(BodyOffsetInputStream.java:73)
	at org.apache.james.mime4j.io.BufferedLineReaderInputStream.fillBuffer(BufferedLineReaderInputStream.java:111)
	at org.apache.james.mime4j.io.BufferedLineReaderInputStream.readLine(BufferedLineReaderInputStream.java:199)
	at org.apache.james.mime4j.io.LineReaderInputStreamAdaptor.readLine(LineReaderInputStreamAdaptor.java:78)
	at org.apache.james.mime4j.stream.MimeEntity.readRawField(MimeEntity.java:215)
	at org.apache.james.mime4j.stream.MimeEntity.nextField(MimeEntity.java:258)
	at org.apache.james.mime4j.stream.MimeEntity.advance(MimeEntity.java:296)
	at org.apache.james.mime4j.stream.MimeTokenStream.next(MimeTokenStream.java:374)
	at org.apache.james.mailbox.store.StoreMessageManager.readHeader(StoreMessageManager.java:384)
	at org.apache.james.mailbox.store.StoreMessageManager.appendMessage(StoreMessageManager.java:330)
	... 47 common frames omitted
Wrapped by: org.apache.james.mailbox.exception.MailboxException: Unable to parse message
	at org.apache.james.mailbox.store.StoreMessageManager.appendMessage(StoreMessageManager.java:346)
	at org.apache.james.imap.processor.AppendProcessor.appendToMailbox(AppendProcessor.java:130)
	at org.apache.james.imap.processor.AppendProcessor.processRequest(AppendProcessor.java:75)
	at org.apache.james.imap.processor.AppendProcessor.processRequest(AppendProcessor.java:55)
	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:100)
	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:77)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:58)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:67)
	at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.messageReceived(ImapChannelUpstreamHandler.java:198)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Reproduction steps

 - Decrease `imapServer.xml` `inMemorySizeLimit` parameter
 - Then append a mail

Example configuration file:

```
<imapservers>
    <imapserver enabled="true">
        <jmxName>imapserver</jmxName>
        <bind>0.0.0.0:0</bind>
        <connectionBacklog>200</connectionBacklog>
        <tls socketTLS="false" startTLS="false">
            <!-- To create a new keystore execute:
            keytool -genkey -alias james -keyalg RSA -keystore /path/to/james/conf/keystore
              -->
            <keystore>file://conf/keystore</keystore>
            <secret>james72laBalle</secret>
            <provider>org.bouncycastle.jce.provider.BouncyCastleProvider</provider>
        </tls>
        <connectionLimit>0</connectionLimit>
        <connectionLimitPerIP>0</connectionLimitPerIP>
        <inMemorySizeLimit>10</inMemorySizeLimit>
    </imapserver>
</imapservers>
```

## Short fix

inMemorySizeLimit defaults to 10 MB which is already quite a lot.

Increasing inMemorySizeLimit would eventually avoid file & FileInputStream miss-management, (at the risk of OOM)

## Possible explanation

See ImapRequestFrameDecoder line 146 the file is deleted upon closing the stream.

The code is *slightly* hard to read and hard to make sense of. But it is likely the file got deleted before it is appended to the store.

**Comment by chibenwa** [comment]
The short fix is working!!!
