### ISSUE TITLE
Flags updates requires the OUTBOX to be present

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3758]
A user ended up with no outbox due to mailbox creation inconsistencies.

This user is not able to update message flags using JMAP

On the server these logs are present:

```
2020.09.07 04:55:47.913 ^[[1;31m[ERROR]^[[0;39m o.a.j.j.d.m.SetMessagesUpdateProcessor - An error occurred when updating a message
org.apache.james.mailbox.exception.MailboxNotFoundException: At least one outbox should be accessible
        at org.apache.james.jmap.draft.methods.SetMessagesUpdateProcessor.isTargetingOutbox(SetMessagesUpdateProcessor.java:294)
        at org.apache.james.jmap.draft.methods.SetMessagesUpdateProcessor.sendMessageWhenOutboxInTargetMailboxIds(SetMessagesUpdateProcessor.java:196)
        at org.apache.james.jmap.draft.methods.SetMessagesUpdateProcessor.update(SetMessagesUpdateProcessor.java:166)
        at org.apache.james.jmap.draft.methods.SetMessagesUpdateProcessor.lambda$prepareResponse$4(SetMessagesUpdateProcessor.java:140)
        at com.google.common.collect.Maps$TransformedEntriesMap.lambda$forEach$0(Maps.java:2078)
```

We should be able to update message flags even when a given user have no outbox

**Comment by chibenwa** [comment]
Merged
