### ISSUE TITLE
Task manager: review error management (cassandra error reported as a deserialization error)

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4083]
```
05:07:52.643 [ERROR] o.a.j.t.e.d.RabbitMQWorkQueue - Unable to deserialize submitted Task b74d18c5-de25-404e-aabf-45dffa505318
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra/192.168.0.4:9042 (com.datastax.driver.core.excepti$
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:284)
        at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:62)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:376)
```

A Cassandra exception gets reported as a deserialization exception. 

We likely have an error management issue.

**Comment by chibenwa** [comment]
Looking at the code, that one is an enigma!
