### ISSUE TITLE
java.lang.IllegalStateException: Status and headers already sent

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4632]
Investigate this:

```
java.lang.IllegalStateException: Status and headers already sent
 at reactor.netty.http.server.HttpServerOperations.status(HttpServerOperations.java:503)
  at org.apache.james.jmap.JMAPRoutes.handleInternalError(JMAPRoutes.java:52)
   at org.apache.james.jmap.http.DownloadRoutes.lambda$get$8(DownloadRoutes.java:179)
    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
      at reactor.core.publisher.Operators.error(Operators.java:198)
       at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
         at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
          at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:195)
           at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
            at reactor.core.publisher.Operators.error(Operators.java:198)
             at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
              at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
               at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
                 at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
                  at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
                   at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onError(MonoUsing.java:260)
                    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
                     at reactor.core.publisher.Operators.error(Operators.java:198)
                      at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
                       at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
                         at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100)
                          at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
                           at reactor.core.publisher.Operators.error(Operators.java:198)
                            at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:56)
                             at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                              at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
                               at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:196)
                                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:268)
                                 at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:270)
                                  at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527)
                                   at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:50)
                                    at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                                     at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384)
                                      at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
                                       at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:348)
                                        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
                                         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
                                          at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                                           at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
                                            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
                                             at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                                              at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                                               at java.base/java.lang.Thread.run(Unknown Source) Suppressed: java.lang.IllegalStateException: Status and headers already sent
                                                at reactor.netty.http.server.HttpServerOperations.status(HttpServerOperations.java:503)
                                                 at org.apache.james.jmap.http.DownloadRoutes.lambda$download$13(DownloadRoutes.java:224)
                                                  at reactor.core.publisher.Mono.lambda$onErrorResume$32(Mono.java:3809)
                                                   at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ... 22 common frames omitted Suppressed: org.apache.james.jmap.draft.exceptions.BlobNotFoundException: Could not retrieve oacfccmcxhqjkshtgsdr
                                                    at org.apache.james.jmap.http.DownloadRoutes.lambda$download$12(DownloadRoutes.java:221)
                                                     at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ... 19 common frames omitted
```

JMAP draft sends headers twice upon errors?

**Comment by chibenwa** [comment]
Scenario:

 - Stack 1: user downloads something that do not exist

 - Stack 2: the response is already sent when returning "not found"

 - Stack 3: We thus handle an internal error but the response headers are already sent...

```
exception	org.apache.james.jmap.draft.exceptions.BlobNotFoundException: Could not retrieve oacfccmcxhqjkshtgsdr
 at org.apache.james.jmap.http.DownloadRoutes.lambda$download$12(DownloadRoutes.java:221)
  at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
   at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
     at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:196)
      at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:268)
       at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:270)
        at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527)
         at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:50)
          at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
           at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384)
            at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
             at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:348)
              at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
               at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
                  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
                   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                     at java.base/java.lang.Thread.run(Unknown Source)

exception	java.lang.IllegalStateException: Status and headers already sent
 at reactor.netty.http.server.HttpServerOperations.status(HttpServerOperations.java:503)
  at org.apache.james.jmap.http.DownloadRoutes.lambda$download$13(DownloadRoutes.java:224)
   at reactor.core.publisher.Mono.lambda$onErrorResume$32(Mono.java:3809)
    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
     at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
      at reactor.core.publisher.Operators.error(Operators.java:198)
       at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:56)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
         at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
          at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:196)
           at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:268)
            at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:270)
             at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527)
              at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:50)
               at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384)
                 at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
                  at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:348)
                   at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
                    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
                     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
                       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
                        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                          at java.base/java.lang.Thread.run(Unknown Source) Suppressed: org.apache.james.jmap.draft.exceptions.BlobNotFoundException: Could not retrieve oacfccmcxhqjkshtgsdr
                           at org.apache.james.jmap.http.DownloadRoutes.lambda$download$12(DownloadRoutes.java:221)
                            at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ... 19 common frames omitted
```

**Comment by chibenwa** [comment]
FIX https://github.com/apache/james-project/pull/1215
