### ISSUE TITLE
JMAP draft download: blocking calls...

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4742]
```
"java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-5
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
at reactor.core.publisher.Mono.block(Mono.java:1710)
at org.apache.james.blob.objectstorage.aws.S3BlobStoreDAO.read(S3BlobStoreDAO.java:201)
at org.apache.james.server.blob.deduplication.DeDuplicationBlobStore.read(DeDuplicationBlobStore.scala:100)
at org.apache.james.blob.cassandra.cache.CachedBlobStore.read(CachedBlobStore.java:140)
at org.apache.james.blob.api.MetricableBlobStore.lambda$read$1(MetricableBlobStore.java:92)
at org.apache.james.metrics.api.MetricFactory.decorateSupplierWithTimerMetric(MetricFactory.java:37)
at org.apache.james.blob.api.MetricableBlobStore.read(MetricableBlobStore.java:92)
at org.apache.james.mailbox.cassandra.mail.CassandraAttachmentMapper.lambda$loadAttachmentContent$1(CassandraAt
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Suppressed: java.lang.Exception: #block terminated with an error
\tat reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:123)
\tat reactor.core.publisher.Mono.blockOptional(Mono.java:1755)
\tat org.apache.james.mailbox.cassandra.mail.CassandraAttachmentMapper.loadAttachmentContent(CassandraAttachmentMapper.java:88)
\tat org.apache.james.mailbox.store.StoreAttachmentManager.loadAttachmentContent(StoreAttachmentManager.java:95)
\tat org.apache.james.jmap.draft.methods.BlobManagerImpl.lambda$loadAttachmentContent$12(BlobManagerImpl.java:161)
\tat org.apache.james.jmap.draft.model.Blob.getStream(Blob.java:111)
\tat reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:997)
\tat reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:253)
\t... 7 common frames omitted\n"
```

TODO investigateWorking on a hotfix...

**Comment by chibenwa** [comment]
chibenwa/tmail-backend-distributed-esv6:0.6.5-debug-2 Uses a BLOCKING-CALL-WRAPPER on JMAP Draft DownloadRoutes line 218

**Comment by chibenwa** [comment]
I ended up reactifying the full chain...

Works!
