### ISSUE TITLE
ASF Jenkins upgrade broke the build

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4748]
```
Pull request #1483 opened

Connecting to https://api.github.com/ using ASF CI for Github PRs etc

Obtained Jenkinsfile from 77cd3c8f391c275b5c177349eb991275ab87e8dd+17f82c39e08167b2d1316277f5be76d4252e9649 (a95c775419c823cf58824cbb7ac9c752a0026ca7)

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

WorkflowScript: 63: Invalid trigger type "issueCommentTrigger". Valid trigger types: [upstream, cron, githubPush, pollSCM] @ line 63, column 9.

           issueCommentTrigger('.*test this please.*')

           ^


1 error


	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)

	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1107)

	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)

	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)

	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)

	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)

	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)

	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox$Scope.parse(GroovySandbox.java:163)

	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)

	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)

	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:563)

	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:515)

	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:336)

	at hudson.model.ResourceController.execute(ResourceController.java:101)

	at hudson.model.Executor.run(Executor.java:442)


GitHub has been notified of this commit’s build result


Finished: FAILURE
```

TODO investigate

**Comment by Arsnael** [comment]
Ok let's remove that method issueCommentTrigger then... it never really worked so not using it anyways

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/projects/INFRA/issues/INFRA-24340 related

**Comment by chibenwa** [comment]
is issueCommentTrigger coming from a plugin???

**Comment by Arsnael** [comment]
Everything is a plugin in Jenkins :) so yeah

**Comment by chibenwa** [comment]
Which plugin is it then?

**Comment by Arsnael** [comment]
https://javadoc.jenkins.io/plugin/pipeline-github/org/jenkinsci/plugins/pipeline/github/trigger/IssueCommentTrigger.html

pipeline-github it seems

**Comment by Arsnael** [comment]
Build is fixed IMO
