### ISSUE TITLE
Mime parsing error

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4767]
[failed.txt](https://github.com/linagora/james-project/files/11257154/failed.txt)

```
Content-Disposition: attachment; 
        filename*=utf-8''4%P001!.DOC;
        filename="4%P001!.DOC"
```

Lead to:

```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: \"P0\"
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at org.apache.james.mime4j.util.MimeParameterMapping.decodeParameterValue(MimeParameterMapping.java:55)
	at org.apache.james.mime4j.util.MimeParameterMapping.addParameter(MimeParameterMapping.java:39)
	at org.apache.james.mime4j.field.ContentDispositionFieldLenientImpl.parse(ContentDispositionFieldLenientImpl.java:165)
	at org.apache.james.mime4j.field.ContentDispositionFieldLenientImpl.getDispositionType(ContentDispositionFieldLenientImpl.java:72)
	at org.apache.james.mime4j.message.MaximalBodyDescriptor.getContentDispositionType(MaximalBodyDescriptor.java:183)
	at org.apache.james.mailbox.opensearch.json.MimePartParser.extractMimePartBodyDescription(MimePartParser.java:133)
	at org.apache.james.mailbox.opensearch.json.MimePartParser.manageBodyExtraction(MimePartParser.java:120)
	at org.apache.james.mailbox.opensearch.json.MimePartParser.processMimePart(MimePartParser.java:87)
	at org.apache.james.mailbox.opensearch.json.MimePartParser.parse(MimePartParser.java:69)
	at org.apache.james.mailbox.opensearch.json.IndexableMessage$Builder.instantiateIndexedMessage(IndexableMessage.java:111)
	at org.apache.james.mailbox.opensearch.json.IndexableMessage$Builder.build(IndexableMessage.java:76)
	at org.apache.james.mailbox.opensearch.json.MessageToOpenSearchJson.convertToJson(MessageToOpenSearchJson.java:74)
	at org.apache.james.mailbox.opensearch.events.OpenSearchListeningMessageSearchIndex.generateIndexedJson(OpenSearchListeningMessageSearchIndex.java:175)
	at org.apache.james.mailbox.opensearch.events.OpenSearchListeningMessageSearchIndex.add(OpenSearchListeningMessageSearchIndex.java:169)
	at org.apache.mailbox.tools.indexer.ReIndexerPerformer.lambda$index$23(ReIndexerPerformer.java:318)
```

Impact: the following message cannot be indexed...

 - 1. Manage the error of James side so the the message is partially indexed (better than nothing!)
 - 2. Thunderbird can get the information, so should MIME4J
 
Unit test + fix there?

![Image](https://user-images.githubusercontent.com/6928740/232649578-39e2d202-9d27-48d0-9be5-970f937f8b6a.png)

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3901 JAMES issue

https://issues.apache.org/jira/browse/MIME4J-324 MIME4J issue

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/1526

https://github.com/apache/james-mime4j/pull/85
