### ISSUE TITLE
PostgresTableManager try to create RLS column even when RLS column existed

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4974]
## Why
Given I have a provisioned Postgres database (with provision tables). I restart James and James can not restart successfully with the following log:

```
james                    | 09:26:49.507 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James
james                    | io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: column "domain" of relation "mailbox" already exists
```

 => Likely upon startup, James tried to alter new RLS column even when the column existed in DB.

## DoD
Propose the fix for `PostgresTableManager`. Tested with unit test or at least manual test.

## Notes

BTW the `PostgresqlBadGrammarException` is used in this case also, not only for the prepareStatement conflict case -> we need to better recognize the prepareStatement conflict case upon retrying PG queries.

**Comment by vttranlina** [comment]
I tried to latest master 77ab188dd6ac66ce0361338f546898cce90babb3
But the issue still not resolved

```java
06:38:02.418 [ERROR] o.a.j.b.p.PostgresTableManager - Error while creating table mailbox
2023-12-11T06:38:02.420553367Z io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: column "domain" of relation "mailbox" already exists
2023-12-11T06:38:02.420556002Z 	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:96)
2023-12-11T06:38:02.420558106Z 	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:65)
2023-12-11T06:38:02.420560230Z 	at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:132)
2023-12-11T06:38:02.420562234Z 	at io.r2dbc.postgresql.PostgresqlResult.lambda$getRowsUpdated$0(PostgresqlResult.java:70)
2023-12-11T06:38:02.420570930Z 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:179)
2023-12-11T06:38:02.420573084Z 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:670)
2023-12-11T06:38:02.420575058Z 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:748)
2023-12-11T06:38:02.420577072Z 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:790)
2023-12-11T06:38:02.420579056Z 	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:241)
2023-12-11T06:38:02.420581080Z 	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:91)
2023-12-11T06:38:02.420583073Z 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2023-12-11T06:38:02.420585057Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
2023-12-11T06:38:02.420587031Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
2023-12-11T06:38:02.420588985Z 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
2023-12-11T06:38:02.420590948Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:684)
2023-12-11T06:38:02.420592922Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:936)
2023-12-11T06:38:02.420594896Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:810)
2023-12-11T06:38:02.420596880Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:716)
2023-12-11T06:38:02.420598873Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
2023-12-11T06:38:02.420601298Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
2023-12-11T06:38:02.420603332Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
2023-12-11T06:38:02.420606398Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
2023-12-11T06:38:02.420608431Z 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292)
2023-12-11T06:38:02.420610465Z 	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:401)
2023-12-11T06:38:02.420612449Z 	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
2023-12-11T06:38:02.420614423Z 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
2023-12-11T06:38:02.420616447Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-12-11T06:38:02.420618460Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-11T06:38:02.420623410Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-11T06:38:02.420625474Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2023-12-11T06:38:02.420627447Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
2023-12-11T06:38:02.420629431Z 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
2023-12-11T06:38:02.420631385Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2023-12-11T06:38:02.420633349Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-12-11T06:38:02.420635312Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-11T06:38:02.420637286Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-11T06:38:02.420639260Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-12-11T06:38:02.420641214Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-12-11T06:38:02.420643177Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-11T06:38:02.420645171Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-12-11T06:38:02.420647255Z 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2023-12-11T06:38:02.420649369Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
2023-12-11T06:38:02.420651323Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-12-11T06:38:02.420653276Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-12-11T06:38:02.420655260Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-12-11T06:38:02.420657214Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-12-11T06:38:02.420659198Z 	at java.base/java.lang.Thread.run(Unknown Source)
2023-12-11T06:38:02.437521852Z 06:38:02.423 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James
2023-12-11T06:38:02.437552520Z io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: column "domain" of relation "mailbox" already exists
2023-12-11T06:38:02.437556547Z 	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:96)
2023-12-11T06:38:02.437559633Z 	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:65)
2023-12-11T06:38:02.437562679Z 	at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:132)
2023-12-11T06:38:02.437578469Z 	at io.r2dbc.postgresql.PostgresqlResult.lambda$getRowsUpdated$0(PostgresqlResult.java:70)
2023-12-11T06:38:02.437581274Z 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:179)
2023-12-11T06:38:02.437584270Z 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:670)
2023-12-11T06:38:02.437587236Z 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:748)
2023-12-11T06:38:02.437589971Z 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:790)
2023-12-11T06:38:02.437592756Z 	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:241)
2023-12-11T06:38:02.437595882Z 	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:91)
2023-12-11T06:38:02.437598968Z 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2023-12-11T06:38:02.437601903Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
2023-12-11T06:38:02.437604749Z 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
2023-12-11T06:38:02.437607684Z 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
2023-12-11T06:38:02.437610530Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:684)
2023-12-11T06:38:02.437613405Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:936)
2023-12-11T06:38:02.437616281Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:810)
2023-12-11T06:38:02.437619046Z 	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:716)
2023-12-11T06:38:02.437621801Z 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
2023-12-11T06:38:02.437625328Z 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
2023-12-11T06:38:02.437628093Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
2023-12-11T06:38:02.437631008Z 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
2023-12-11T06:38:02.437633944Z 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292)
2023-12-11T06:38:02.437636649Z 	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:401)
2023-12-11T06:38:02.437639535Z 	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
2023-12-11T06:38:02.437642300Z 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
2023-12-11T06:38:02.437645105Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-12-11T06:38:02.437647971Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-11T06:38:02.437655234Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-11T06:38:02.437658010Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2023-12-11T06:38:02.437660745Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
2023-12-11T06:38:02.437663400Z 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
2023-12-11T06:38:02.437666105Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2023-12-11T06:38:02.437668820Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-12-11T06:38:02.437671595Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-11T06:38:02.437674290Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-11T06:38:02.437706742Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-12-11T06:38:02.437722582Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-12-11T06:38:02.437733382Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-11T06:38:02.437738672Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-12-11T06:38:02.437741949Z 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2023-12-11T06:38:02.437744734Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
2023-12-11T06:38:02.437747429Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-12-11T06:38:02.437749964Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-12-11T06:38:02.437752649Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-12-11T06:38:02.437755284Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-12-11T06:38:02.437757999Z 	at java.base/java.lang.Thread.run(Unknown Source)
2023-12-11T06:38:02.437760574Z 	Suppressed: java.lang.Exception: #block terminated with an error
2023-12-11T06:38:02.437763159Z 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2023-12-11T06:38:02.437765924Z 		at reactor.core.publisher.Mono.block(Mono.java:1712)
2023-12-11T06:38:02.437768529Z 		at org.apache.james.backends.postgres.PostgresTableManager.initPostgres(PostgresTableManager.java:63)
2023-12-11T06:38:02.437771184Z 		at org.apache.james.backends.postgres.PostgresTableManager.<init>(PostgresTableManager.java:49)
2023-12-11T06:38:02.437779510Z 		at org.apache.james.modules.data.PostgresCommonModule.postgresTableManager(PostgresCommonModule.java:103)
2023-12-11T06:38:02.437782355Z 		at org.apache.james.modules.data.PostgresCommonModule$$FastClassByGuice$$cc7470.GUICE$TRAMPOLINE(<generated>)
```

**Comment by vttranlina** [comment]
> Does your branch contain the commit `JAMES-2586 Small codestyle refactorings`, and have you rebuilt the image?

yes, it has
The test cases still passed `recreateRLSColumnWhenExistedShouldNotFail`,
But rebuild image it failed, weird

**Comment by vttranlina** [comment]
- Current way: always create columns, and policies for each start. After that ignore the exception 
- Another alternative is to check whether the column/policy exists or not, and then will alter or nothing 
Pr: https://github.com/apache/james-project/pull/1848
