### ISSUE TITLE
Demo sprint 36

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4996]
Demo: IMAP server with postgres-app distributed version (S3, RabbitMQ event bus, OpenSearch)

**Comment by quantranhong1999** [comment]
https://github.com/linagora/james-project/assets/55171818/28310788-97b1-4db0-9bba-d6df5f395a85

**Comment by quantranhong1999** [comment]
There is an error regarding `RabbitMQEventBusDeadLetterQueueHealthCheck`:
```java
james                    | 03:33:57.605 [ERROR] o.a.j.PeriodicalHealthChecks - HealthCheck error. Triggering value: MonoCallable, Cause:
james                    | java.lang.RuntimeException: Non recoverable exception status: 404
james                    |      at org.apache.james.backends.rabbitmq.RabbitMQManagementAPI.lambda$static$3(RabbitMQManagementAPI.java:439)
james                    |      at feign.ResponseHandler.decodeError(ResponseHandler.java:136)
james                    |      at feign.ResponseHandler.handleResponse(ResponseHandler.java:70)
james                    |      at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114)
james                    |      at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
james                    |      at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96)
james                    |      at com.sun.proxy.$Proxy35.queueDetails(Unknown Source)
james                    |      at org.apache.james.events.RabbitMQEventBusDeadLetterQueueHealthCheck.lambda$check$1(RabbitMQEventBusDeadLetterQueueHealthCheck.java:56)
```

I will investigate this.

**Comment by quantranhong1999** [comment]
> I will investigate this.

Well, it failed because there is no Jmap Event bus dead letter queue - which is obvious as we do not plug JMAP yet.

**Comment by quantranhong1999** [comment]
I think we should not plug the JMAP event bus queue/health check when JMAP is disabled, and propose fix for it:
- master branch: https://github.com/apache/james-project/pull/1886
- postgreql branch: https://github.com/apache/james-project/pull/1885

**Comment by Arsnael** [comment]
Good catch!

Very complete detailed demo as well, cheers on that <3
