### ISSUE TITLE
[PGSL] Investigate why CI fail and fix - PostgresQuotaSearchIntegrationTest

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5045]
## How to re-produce
- git checkout latest apache/postgresql
- maven build
- Run test `org.apache.james.webadmin.integration.postgres.PostgresQuotaSearchIntegrationTest` 

Test fail at: quotaSearchShouldPlayWellWithDelegation

```
quotaSearchShouldPlayWellWithDelegation(GuiceJamesServer) – org.apache.james.webadmin.integration.postgres.PostgresQuotaSearchIntegrationTest
3s
Error
1 expectation failed.
JSON path username doesn't match.
Expected: iterable with items ["cedric@domain.tld"] in any order
  Actual: <[]>
Stacktrace
java.lang.AssertionError: 
1 expectation failed.
JSON path username doesn't match.
Expected: iterable with items ["cedric@domain.tld"] in any order
  Actual: <[]>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
	at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:270)
```

**Comment by vttranlina** [comment]
The issue from missing guice binding when implement PostgresEmailChange, (maybe do it parallel, and merge 2 pr in time, so we lack CI it)
Commit fixit: https://github.com/apache/james-project/pull/1937/commits/6838fb653b5865e0b7b2f29258758c6fad66a237

**Comment by Arsnael** [comment]
Can you make a PR for this fix? I only see a commit from outside the repo :)

**Comment by vttranlina** [comment]
yes, pr it https://github.com/apache/james-project/pull/1937

**Comment by Arsnael** [comment]
Yep just saw it and merged it. Thanks for the fix :)
