### ISSUE TITLE
MailReceptionCheck: data race

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5049]
```
reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56)
	at org.apache.james.healthcheck.MailReceptionCheck$AwaitReceptionListener.lambda$reactiveEvent$0(MailReceptionCheck.java:171)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Root cause: the listener is being called concurrently while it should not.

Fix proposition: a lock on boundedElastic in order to synchronise sink production?

Help from the team welcomed on that issue.

**Comment by vttranlina** [comment]
## How to re-produce
```java
//MailReceptionCheck.class
public static void main(String[] args) {
        AwaitReceptionListener listener = new AwaitReceptionListener();
        MailboxEvents.Added event = new MailboxEvents.Added(MailboxSession.SessionId.of(42),
            Username.of("bob"),
            MailboxPath.forUser(Username.of("bob"), "Outbox"),
            InMemoryId.of(1),
            ImmutableSortedMap.of(MessageUid.of(1), new MessageMetaData(MessageUid.of(1),
                ModSeq.of(35), new Flags(), 12,
                new Date(),
                Optional.empty(),
                InMemoryMessageId.of(1),
                ThreadId.fromBaseMessageId(InMemoryMessageId.of(1)))),
            Event.EventId.random(),
            false,
            false,
            Optional.empty());

        Flux.range(0, 1_000_000)
            .flatMap(i -> listener.reactiveEvent(event), 100)
            .then()
            .block();

        System.out.println("MailReceptionCheck: done");
    }

```

**Comment by vttranlina** [comment]
> Fix proposition: a lock on boundedElastic in order to synchronise sink production?

The `Schedulers.single` is ok?

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/1980 

Sorry, here's a fix.

Apparently I forgot to open a PR...

**Comment by chibenwa** [comment]
> The Schedulers.single is ok?

single I think do not allow blocking calls ...
