### ISSUE TITLE
java.nio.file.NoSuchFileException: /tmp/imap-literal2808491105678124450.tmp

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5073]
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.github.fge.lambdas.ThrownByLambdaException: java.nio.file.NoSuchFileException: /tmp/imap-literal2808491105678124450.tmp
Caused by: com.github.fge.lambdas.ThrownByLambdaException: java.nio.file.NoSuchFileException: /tmp/imap-literal2808491105678124450.tmp
	at com.github.fge.lambdas.runnable.ThrowingRunnable.run(ThrowingRunnable.java:20)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: /tmp/imap-literal2808491105678124450.tmp
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at org.apache.james.imapserver.netty.NettyStreamImapRequestLineReader$FileLiteral.lambda$close$0(NettyStreamImapRequestLineReader.java:60)
	at com.github.fge.lambdas.runnable.RunnableChainer.doRun(RunnableChainer.java:18)
	at com.github.fge.lambdas.runnable.ThrowingRunnable.run(ThrowingRunnable.java:16)
	... 10 common frames omitted
```

My takes: the connection is likely closed after receiving the all file but before we process it.

This could be because of a customer timeout at 30 seconds. (saw some slow as f****** S3 requests)

Please confirm this log by trying it yourself.

We could think of a keepalive timer while appending the file, and that only for biiig files?

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/2035

**Comment by chibenwa** [comment]
This still happens after https://github.com/apache/james-project/pull/2035

**Comment by chibenwa** [comment]
But https://github.com/apache/james-project/pull/2052 likely did!
