### ISSUE TITLE
ContentDispositionFieldLenientImpl is not as lenient as it seems...

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5080]
```
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at org.apache.james.mime4j.util.MimeParameterMapping.decodeParameterValue(MimeParameterMapping.java:55)
	at org.apache.james.mime4j.util.MimeParameterMapping.addParameter(MimeParameterMapping.java:39)
	at org.apache.james.mime4j.field.ContentDispositionFieldLenientImpl.parse(ContentDispositionFieldLenientImpl.java:165)
	at org.apache.james.mime4j.field.ContentDispositionFieldLenientImpl.getDispositionType(ContentDispositionFieldLenientImpl.java:72)
	at org.apache.james.mime4j.message.MaximalBodyDescriptor.getContentDispositionType(MaximalBodyDescriptor.java:183)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.createDescriptor(MimeDescriptorImpl.java:187)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.desctriptorWithoutSize(MimeDescriptorImpl.java:161)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.simplePartDescriptor(MimeDescriptorImpl.java:130)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.createDescriptor(MimeDescriptorImpl.java:85)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.compositePartDescriptor(MimeDescriptorImpl.java:108)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.createDescriptor(MimeDescriptorImpl.java:88)
	at org.apache.james.mailbox.store.MimeDescriptorImpl.build(MimeDescriptorImpl.java:66)
	at org.apache.james.mailbox.store.MessageResultImpl.getMimeDescriptor(MessageResultImpl.java:294)
	at org.apache.james.imap.processor.fetch.FetchResponseBuilder.lambda$build$1(FetchResponseBuilder.java:168)
	at org.apache.james.mailbox.NullableMessageSequenceNumber.fold(NullableMessageSequenceNumber.java:62)
	at org.apache.james.imap.processor.fetch.FetchResponseBuilder.build(FetchResponseBuilder.java:125)
	at org.apache.james.imap.processor.fetch.FetchProcessor.toResponse(FetchProcessor.java:258)
	at org.apache.james.imap.processor.fetch.FetchProcessor.lambda$processMessageRanges$18(FetchProcessor.java:209)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

## Definition of done: 

Reproduce and fix in mime4j...

**Comment by chibenwa** [comment]
It is not in MIME4J `0.8.9` but it is with `0.8.10`.
