### ISSUE TITLE
IMAP: java.util.NoSuchElementException: requestDecoder

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5084]
```
java.util.NoSuchElementException: requestDecoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at org.apache.james.imapserver.netty.ImapRequestFrameDecoder.enableFraming(ImapRequestFrameDecoder.java:337)
	at org.apache.james.imapserver.netty.ImapRequestFrameDecoder.parseImapMessage(ImapRequestFrameDecoder.java:143)
	at org.apache.james.imapserver.netty.ImapRequestFrameDecoder.lambda$uploadToAFile$0(ImapRequestFrameDecoder.java:223)
	at org.apache.james.imapserver.netty.ImapRequestFrameDecoder$FileChunkConsumer.finalizeDataTransfer(ImapRequestFrameDecoder.java:313)
	at org.apache.james.imapserver.netty.ImapRequestFrameDecoder$FileChunkConsumer.accept(ImapRequestFrameDecoder.java:273)
	at org.apache.james.imapserver.netty.ImapRequestFrameDecoder$FileChunkConsumer.accept(ImapRequestFrameDecoder.java:250)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by chibenwa** [comment]
This do not happen all the time so I suspect a race condition of some kind

**Comment by chibenwa** [comment]
CF https://github.com/apache/james-project/pull/2061
