### ISSUE TITLE
Audit log: better handle missing mime message id

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5090]
```
java.lang.NullPointerException: null value in entry: mimeMessageId=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:341)
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:158)
	at com.linagora.tmail.mailets.TmailLocalDelivery.$anonfun$service$1(TmailLocalDelivery.scala:39)
	at org.apache.james.util.AuditTrail$Entry.parameters(AuditTrail.java:102)
	at com.linagora.tmail.mailets.TmailLocalDelivery.service(TmailLocalDelivery.scala:35)
```

Avoid that warning?

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-backend/pull/936
