### ISSUE TITLE
javax.mail.internet.AddressException: Invalid character in local-part (user account) at position 3 in 'Maître XXX YYY'

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5091]
```
javax.mail.internet.AddressException: Invalid character in local-part (user account) at position 3 in 'Maître XXX YYY'
	at org.apache.james.core.MailAddress.parseUnquotedLocalPart(MailAddress.java:524)
	at org.apache.james.core.MailAddress.parseUnquotedLocalPartOrThrowException(MailAddress.java:259)
	at org.apache.james.core.MailAddress.<init>(MailAddress.java:189)
	at org.apache.james.core.MaybeSender.getMailSender(MaybeSender.java:47)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.apache.james.vault.metadata.DeletedMessageVaultDeletionCallback.retrieveSender(DeletedMessageVaultDeletionCallback.java:124)
	at org.apache.james.vault.metadata.DeletedMessageVaultDeletionCallback.lambda$forMessage$2(DeletedMessageVaultDeletionCallback.java:85)
```

Sender header might be missing. Use `From` header instead.

INFO log also

**Comment by Arsnael** [comment]
PR link?

**Comment by chibenwa** [comment]
Sorry likely a mistake

**Comment by chibenwa** [comment]
LOG level was switched to INFO
