### ISSUE TITLE
java.lang.IllegalArgumentException: Mime charser '' doesn't have a corresponding Java charset (=??Q?Sans_titre=2Eeml_=281=2C20=C2=A0Mo=29?=)

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5106]
```
java.lang.IllegalArgumentException: Mime charser '' doesn't have a corresponding Java charset (=??Q?Sans_titre=2Eeml_=281=2C20=C2=A0Mo=29?=)
	at org.apache.james.mime4j.codec.DecoderUtil.monitor(DecoderUtil.java:331)
	at org.apache.james.mime4j.codec.DecoderUtil.tryDecodeEncodedWord(DecoderUtil.java:273)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeEncodedWords(DecoderUtil.java:249)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeEncodedWords(DecoderUtil.java:158)
	at org.apache.james.mime4j.stream.RawFieldParser.copyQuotedContent(RawFieldParser.java:443)
	at org.apache.james.mime4j.stream.RawFieldParser.parseValue(RawFieldParser.java:219)
	at org.apache.james.mime4j.stream.RawFieldParser.parseParameter(RawFieldParser.java:148)
	at org.apache.james.mime4j.stream.RawFieldParser.parseParameters(RawFieldParser.java:125)
	at org.apache.james.mime4j.stream.RawFieldParser.parseRawBody(RawFieldParser.java:110)
	at org.apache.james.mime4j.stream.RawFieldParser.parseRawBody(RawFieldParser.java:95)
	at org.apache.james.mime4j.field.ContentTypeFieldLenientImpl.parse(ContentTypeFieldLenientImpl.java:112)
	at org.apache.james.mime4j.field.ContentTypeFieldLenientImpl.getMimeType(ContentTypeFieldLenientImpl.java:54)
	at org.apache.james.mime4j.message.DefaultBodyDescriptorBuilder.build(DefaultBodyDescriptorBuilder.java:106)
	at org.apache.james.mime4j.stream.MimeEntity.advance(MimeEntity.java:315)
	at org.apache.james.mime4j.stream.MimeTokenStream.next(MimeTokenStream.java:375)
	at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:177)
	at org.apache.james.mime4j.message.DefaultMessageBuilder.parseMessage(DefaultMessageBuilder.java:321)
	at org.apache.james.jmap.api.model.Preview$Factory.parse(Preview.java:86)
	at org.apache.james.jmap.api.model.Preview$Factory.fromInputStream(Preview.java:67)
	at org.apache.james.jmap.api.model.Preview$Factory.fromMessageResult(Preview.java:58)
	at org.apache.james.jmap.api.projections.MessageFastViewPrecomputedProperties$Factory.from(MessageFastViewPrecomputedProperties.java:87)
	at org.apache.james.jmap.event.ComputeMessageFastViewProjectionListener.computeFastViewPrecomputedProperties(ComputeMessageFastViewProjectionListener.java:115)
	at org.apache.james.jmap.event.ComputeMessageFastViewProjectionListener.lambda$handleAddedEvent$0(ComputeMessageFastViewProjectionListener.java:107)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Be more lenient?

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/MIME4J-326

**Comment by chibenwa** [comment]
https://github.com/apache/james-mime4j/pull/97

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/2073
