### ISSUE TITLE
java.lang.Error: java.io.IOException: Unexpected end of BASE64 stream

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5107]
```
java.lang.Error: java.io.IOException: Unexpected end of BASE64 stream
	at org.apache.james.mime4j.codec.DecoderUtil.decodeBase64(DecoderUtil.java:104)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeB(DecoderUtil.java:121)
	at org.apache.james.mime4j.codec.DecoderUtil.tryDecodeEncodedWord(DecoderUtil.java:288)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeEncodedWords(DecoderUtil.java:249)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeEncodedWords(DecoderUtil.java:158)
	at org.apache.james.mime4j.stream.RawFieldParser.copyQuotedContent(RawFieldParser.java:443)
	at org.apache.james.mime4j.stream.RawFieldParser.parseValue(RawFieldParser.java:219)
	at org.apache.james.mime4j.field.address.LenientAddressParser.parseAddress(LenientAddressParser.java:274)
	at org.apache.james.mime4j.field.address.LenientAddressParser.parseAddressList(LenientAddressParser.java:319)
	at org.apache.james.mime4j.field.address.LenientAddressParser.parseAddressList(LenientAddressParser.java:331)
	at org.apache.james.mailbox.opensearch.json.HeaderCollection$Builder.manageAddressField(HeaderCollection.java:151)
	at org.apache.james.mailbox.opensearch.json.HeaderCollection$Builder.handleSpecificHeader(HeaderCollection.java:134)
	at org.apache.james.mailbox.opensearch.json.HeaderCollection$Builder.add(HeaderCollection.java:110)
	at org.apache.james.mailbox.opensearch.json.MimePart$Builder.addToHeaders(MimePart.java:80)
	at org.apache.james.mailbox.opensearch.json.MimePart$Builder.addToHeaders(MimePart.java:52)
	at org.apache.james.mailbox.opensearch.json.MimePartParser.processMimePart(MimePartParser.java:84)
	at org.apache.james.mailbox.opensearch.json.MimePartParser.parse(MimePartParser.java:69)
	at org.apache.james.mailbox.opensearch.json.IndexableMessage$Builder.instantiateIndexedMessage(IndexableMessage.java:111)
	at org.apache.james.mailbox.opensearch.json.IndexableMessage$Builder.build(IndexableMessage.java:76)
	at org.apache.james.mailbox.opensearch.json.MessageToOpenSearchJson.convertToJson(MessageToOpenSearchJson.java:81)
	at org.apache.james.mailbox.opensearch.events.OpenSearchListeningMessageSearchIndex.generateIndexedJson(OpenSearchListeningMessageSearchIndex.java:345)
	at org.apache.james.mailbox.opensearch.events.OpenSearchListeningMessageSearchIndex.add(OpenSearchListeningMessageSearchIndex.java:333)
	at org.apache.james.mailbox.store.search.ListeningMessageSearchIndex.lambda$handleAdded$6(ListeningMessageSearchIndex.java:129)
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Unexpected end of BASE64 stream
	at org.apache.james.mime4j.codec.Base64InputStream.handleUnexpectedEof(Base64InputStream.java:296)
	at org.apache.james.mime4j.codec.Base64InputStream.read0(Base64InputStream.java:185)
	at org.apache.james.mime4j.codec.Base64InputStream.read(Base64InputStream.java:103)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeBase64(DecoderUtil.java:94)
	... 32 common frames omitted
```

**Comment by chibenwa** [comment]
```
Return-Path: <ccc@xxx.co.ua>\r\nDelivered-To: 3@5370\r\n
Message-ID: <c17b01d3fcc5$f18357f0$b3d61d9f@atfilpd>
Reply-To: "=?windows-1251?B?oyyiyxvowqoztnirveljj?=" <atfilpd@louisphaethon.co.ua>
From: "=?windows-1251?B?onsonsmekqixrbahkinyv?=" <atfilpd@louisphaethon.co.ua>
To: <hdj.vacola@asso-gd.fr>
Subject: =?windows-1251?B?ewnitrpynnaxzwaqsyqprizbizfk?=
Date: Tue, 05 Jun 2018 12:08:41 +0300
MIME-Version: 1.0
Content-Type: text/plain;\r\n\tcharset="windows-1251"
Content-Transfer-Encoding: 7bit
X-MimeOLE: Produced By Microsoft MimeOLE V14.0.8117.416
```

**Comment by chibenwa** [comment]
At the very least:

 - Write a reproduction test
 - HeaderCollection likely should swallow the exception...

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/MIME4J-326

**Comment by chibenwa** [comment]
https://github.com/apache/james-mime4j/pull/97

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/2073
