### ISSUE TITLE
[BUG] Missing guice binding JsonEventSerializer for PostgresEventStoreDAO

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5143]
When testing on local
I got an error
```
org.apache.james.eventsourcing.eventstore.JsonEventSerializer$UnknownEventException: org.apache.james.json.JsonGenericSerializer$UnknownTypeException: unknown type class org.apache.james.jmap.api.filtering.impl.IncrementalRuleChange
	at org.apache.james.eventsourcing.eventstore.JsonEventSerializer.serialize(JsonEventSerializer.scala:76)
	at org.apache.james.eventsourcing.eventstore.postgres.PostgresEventStoreDAO.convertToJooqJson(PostgresEventStoreDAO.java:78)
```

It looks like we missing guice binding for creating instance [JsonEventSerializer](https://github.com/apache/james-project/blob/78aa40b2c7b428453a9422caf5f4109f4ef6a758/event-sourcing/event-store-api/src/main/scala/org/apache/james/eventsourcing/eventstore/JsonEventSerializer.scala#L64)

The `modules: util.Set[EventDTOModule[_ <: Event, _ <: EventDTO]]` has size = 1, it quite smell, (for cassandra, it has size 15)

**Comment by vttranlina** [comment]
How to reproduce?
- can run any Postgres webadmin integration, and debug on the init structure `PostgresEventStoreDAO`

**Comment by vttranlina** [comment]
After update guice binding in sporadic pull requests
It looks normal now

```
modules size : 13
nestedTypesModules size : 62
```
