### ISSUE TITLE
Error when start distributed app with docker-compose-with-pulsar

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5155]
When start-up docker-compose 
https://github.com/apache/james-project/blob/96210bd6eb2cc17b01aba6de304191b7eb83ba99/server/apps/distributed-app/docker-compose-with-pulsar.yml

It print error:
```java
10:12:48.356 [WARN ] o.a.p.c.u.n.DnsResolverUtil - Cannot get DNS TTL settings from sun.net.InetAddressCachePolicy class
2024-04-05T10:12:48.357354013Z java.lang.IllegalAccessException: class org.apache.pulsar.common.util.netty.DnsResolverUtil cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @238d7bbb
2024-04-05T10:12:48.357356889Z 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
2024-04-05T10:12:48.357359093Z 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
2024-04-05T10:12:48.357368381Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-04-05T10:12:48.357370615Z 	at org.apache.pulsar.common.util.netty.DnsResolverUtil.<clinit>(DnsResolverUtil.java:46)
2024-04-05T10:12:48.357372729Z 	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:159)
2024-04-05T10:12:48.357374753Z 	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:126)
2024-04-05T10:12:48.357376766Z 	at java.base/java.util.Optional.orElseGet(Unknown Source)
2024-04-05T10:12:48.357378800Z 	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:126)
2024-04-05T10:12:48.357380914Z 	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95)
2024-04-05T10:12:48.357382928Z 	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90)
2024-04-05T10:12:48.357384922Z 	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:198)
2024-04-05T10:12:48.357386976Z 	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:154)
2024-04-05T10:12:48.357389010Z 	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63)
2024-04-05T10:12:48.357411492Z 	at com.sksamuel.pulsar4s.PulsarClient$.apply(PulsarClient.scala:228)
2024-04-05T10:12:48.357459563Z 	at org.apache.james.backends.pulsar.PulsarClients$.create(PulsarClients.scala:50)
2024-04-05T10:12:48.357509057Z 	at org.apache.james.backends.pulsar.PulsarClients.create(PulsarClients.scala)
2024-04-05T10:12:48.357532862Z 	at org.apache.james.queue.pulsar.module.PulsarQueueModule.pulsarClients(PulsarQueueModule.java:79)
2024-04-05T10:12:48.357575513Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
2024-04-05T10:12:48.357601031Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-04-05T10:12:48.357621560Z 	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:284)
2024-04-05T10:12:48.357642570Z 	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
2024-04-05T10:12:48.357664972Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
2024-04-05T10:12:48.357690591Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
2024-04-05T10:12:48.357718974Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.357748590Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.357765552Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.357803795Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.357829824Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.357852958Z 	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
2024-04-05T10:12:48.357878697Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
2024-04-05T10:12:48.357947667Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
2024-04-05T10:12:48.358044400Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.358075179Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.358129021Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.358177402Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.358214322Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.358276510Z 	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
2024-04-05T10:12:48.358321876Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
2024-04-05T10:12:48.358360529Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
2024-04-05T10:12:48.358389704Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.358426514Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.358473312Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.358508579Z 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
2024-04-05T10:12:48.358539888Z 	at org.apache.james.queue.pulsar.module.PulsarQueueModule.mailQueue(PulsarQueueModule.java:119)
2024-04-05T10:12:48.358581888Z 	at org.apache.james.queue.pulsar.module.PulsarQueueModule$$FastClassByGuice$$36d0259.GUICE$TRAMPOLINE(<generated>)
2024-04-05T10:12:48.358621282Z 	at org.apache.james.queue.pulsar.module.PulsarQueueModule$$FastClassByGuice$$36d0259.apply(<generated>)
2024-04-05T10:12:48.358657150Z 	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
2024-04-05T10:12:48.358691465Z 	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
2024-04-05T10:12:48.358723496Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
2024-04-05T10:12:48.358759945Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
2024-04-05T10:12:48.358805601Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.358839195Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.358862389Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.358891744Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.358925578Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.358955856Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2024-04-05T10:12:48.358984039Z 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
2024-04-05T10:12:48.359011551Z 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2024-04-05T10:12:48.359031960Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
2024-04-05T10:12:48.359062478Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:124)
2024-04-05T10:12:48.359085962Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2024-04-05T10:12:48.359117081Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2024-04-05T10:12:48.359146206Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
2024-04-05T10:12:48.359170642Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.359199647Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.359235094Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.359263729Z 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
2024-04-05T10:12:48.359292343Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.359327950Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.359372855Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2024-04-05T10:12:48.359422459Z 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
2024-04-05T10:12:48.359455852Z 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2024-04-05T10:12:48.359481932Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
2024-04-05T10:12:48.359514954Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:124)
2024-04-05T10:12:48.359546093Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2024-04-05T10:12:48.359565580Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2024-04-05T10:12:48.359624862Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
2024-04-05T10:12:48.359628189Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.359630924Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.359633689Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.359637115Z 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
2024-04-05T10:12:48.359639871Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.359642486Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.359645391Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2024-04-05T10:12:48.359648156Z 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
2024-04-05T10:12:48.359651022Z 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2024-04-05T10:12:48.359653897Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
2024-04-05T10:12:48.359656763Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:124)
2024-04-05T10:12:48.359659708Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2024-04-05T10:12:48.359662544Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2024-04-05T10:12:48.359665339Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
2024-04-05T10:12:48.359668244Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2024-04-05T10:12:48.359671020Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
2024-04-05T10:12:48.359673885Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
2024-04-05T10:12:48.359676640Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.359679476Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.359682311Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2024-04-05T10:12:48.359691128Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
2024-04-05T10:12:48.359693903Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
2024-04-05T10:12:48.359696728Z 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
2024-04-05T10:12:48.359699564Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.359703000Z 	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:263)
2024-04-05T10:12:48.359705846Z 	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:229)
2024-04-05T10:12:48.359708671Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113)
2024-04-05T10:12:48.359711486Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
2024-04-05T10:12:48.359714372Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
2024-04-05T10:12:48.359717097Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2024-04-05T10:12:48.359719812Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
2024-04-05T10:12:48.359722557Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
2024-04-05T10:12:48.359725373Z 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
2024-04-05T10:12:48.359728068Z 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
2024-04-05T10:12:48.359730913Z 	at org.apache.james.GuiceJamesServer.start(GuiceJamesServer.java:88)
2024-04-05T10:12:48.359792079Z 	at org.apache.james.JamesServerMain.main(JamesServerMain.java:30)
2024-04-05T10:12:48.359797930Z 	at org.apache.james.CassandraRabbitMQJamesServerMain.main(CassandraRabbitMQJamesServerMain.java:194)
```

Investigate and fix  it

**Comment by vttranlina** [comment]
resolved,
Can not re-produce it 
![Image](https://github.com/user-attachments/assets/0076bdda-218a-42fe-98e8-f1b778e09e35)
