### ISSUE TITLE
jakarta.mail.internet.AddressException: Empty address in string ``''

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5264]
Likely a bounce.

We should make sure `MAIL FROM :<>` are accepted...

```
java.lang.RuntimeException: jakarta.mail.internet.AddressException: Empty address in string ``''
	at org.apache.james.smtpserver.SenderAuthIdentifyVerificationHook.onMessage(SenderAuthIdentifyVerificationHook.java:144)
	at org.apache.james.smtpserver.DataLineJamesMessageHookHandler.executeJamesMessageHooks(DataLineJamesMessageHookHandler.java:215)
	at org.apache.james.smtpserver.DataLineJamesMessageHookHandler.processExtensions(DataLineJamesMessageHookHandler.java:197)
	at org.apache.james.smtpserver.DataLineJamesMessageHookHandler.onLine(DataLineJamesMessageHookHandler.java:114)
	at org.apache.james.protocols.smtp.core.DataCmdHandler$DataLineFilterWrapper.onLine(DataCmdHandler.java:87)
	at org.apache.james.protocols.smtp.core.DataCmdHandler$DataLineFilterWrapper.onLine(DataCmdHandler.java:75)
	at org.apache.james.protocols.smtp.core.SeparatingDataLineFilter.onBodyLine(SeparatingDataLineFilter.java:100)
	at org.apache.james.protocols.smtp.core.SeparatingDataLineFilter.onLine(SeparatingDataLineFilter.java:58)
	at org.apache.james.protocols.smtp.core.DataCmdHandler$DataLineFilterWrapper.onLine(DataCmdHandler.java:87)
	at org.apache.james.protocols.smtp.core.DataCmdHandler$DataLineFilterWrapper.onLine(DataCmdHandler.java:75)
	at org.apache.james.protocols.smtp.core.esmtp.MailSizeEsmtpExtension.onLine(MailSizeEsmtpExtension.java:150)
	at org.apache.james.protocols.smtp.core.DataCmdHandler$DataLineFilterWrapper.onLine(DataCmdHandler.java:87)
	at org.apache.james.protocols.smtp.core.DataCmdHandler$DataLineFilterWrapper.onLine(DataCmdHandler.java:75)
	at org.apache.james.protocols.netty.LineHandlerUpstreamHandler.channelRead(LineHandlerUpstreamHandler.java:52)
	at org.apache.james.protocols.netty.BasicChannelInboundHandler.channelRead(BasicChannelInboundHandler.java:177)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: jakarta.mail.internet.AddressException: Empty address
	at jakarta.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1260)
	at jakarta.mail.internet.InternetAddress.parse(InternetAddress.java:1200)
	at jakarta.mail.internet.InternetAddress.parseHeader(InternetAddress.java:762)
	at jakarta.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:751)
	at jakarta.mail.internet.MimeMessage.getFrom(MimeMessage.java:373)
	at org.apache.james.smtpserver.SenderAuthIdentifyVerificationHook.onMessage(SenderAuthIdentifyVerificationHook.java:138)
	... 27 common frames omitted
```

Associated conf:

```
<smtpservers>
  <smtpserver enabled="${env:TMAIL_IMAP_SMTP_ENABLED}">
    <jmxName>smtpserver-global</jmxName>
    <bind>0.0.0.0:25</bind>
    <connectionBacklog>200</connectionBacklog>
    <tls socketTLS="false" startTLS="true">
      <privateKey>file://secrets/smtp/tls.key</privateKey>
      <certificates>file://secrets/smtp/tls.crt</certificates>
    </tls>
    <authorizedAddresses>100.96.59.120/32,100.96.74.171/32,100.96.74.172/32,87.255.138.193/32,87.255.138.194/32</authorizedAddresses>
    <helloName autodetect="false">${env:TMAIL_DOMAIN_SMTP}</helloName>
    <connectiontimeout>360</connectiontimeout>
    <connectionLimit>0</connectionLimit>
    <connectionLimitPerIP>0</connectionLimitPerIP>
    <authRequired>false</authRequired>
    <verifyIdentity>true</verifyIdentity>
    <proxyRequired>true</proxyRequired>
    <maxmessagesize>${env:TMAIL_MESSAGE_SIZE}</maxmessagesize>
    <addressBracketsEnforcement>true</addressBracketsEnforcement>
    <smtpGreeting>${env:TMAIL_SMTP_MESSAGE}</smtpGreeting>
    <ioWorkerCount>1</ioWorkerCount>
    <maxExecutorCount>4</maxExecutorCount>
    <handlerchain>
      <handler class="com.linagora.tmail.smtp.TMailValidRcptHandler"/>
      <handler class="org.apache.james.smtpserver.CoreCmdHandlerLoader"/>
    </handlerchain>
  </smtpserver>
```

## definition of done

Integration test (mailet integration test we have there some SMTP tests for this.

Make sure we accept those value.

**Comment by chibenwa** [comment]
Note about what happens:

The email RCPT TO command likely is right

However the `From` header is likely invalid

![image](https://github.com/user-attachments/assets/8ca1a619-d001-4cee-ba7c-3fdd4ea2b4aa)

This asumption is false.

Instead of throwing we likely can return "false" (the from field is invalid and is not a valid mail address)

I'm hot patching prod (cause some mails are being dropped!), please provide a clean tested patch for master branch.

**Comment by quantranhong1999** [comment]
Fix: https://github.com/apache/james-project/pull/2400
