### ISSUE TITLE
[MU] POP3: java.lang.ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5376]
These two error logs come together:

```json
{
    "timestamp": "2024-12-19T07:23:30.193Z",
    "level": "ERROR",
    "thread": "pop3server-7",
    "mdc": {
        "charset": "US-ASCII",
        "protocol": "POP3",
        "sessionId": "a862128f",
        "user": "mrbadal@govmu.org",
        "ip": "192.168.43.3"
    },
    "logger": "org.apache.james.util.MDCBuilder",
    "message": "Got error, logging its context",
    "context": "default",
    "exception": "java.lang.ArrayIndexOutOfBoundsException: null\n"
}
```

```json
{
    "timestamp": "2024-12-19T07:23:30.193Z",
    "level": "ERROR",
    "thread": "pop3server-7",
    "mdc": {
        "charset": "US-ASCII",
        "protocol": "POP3",
        "sessionId": "a862128f",
        "user": "mrbadal@govmu.org",
        "ip": "192.168.43.3"
    },
    "logger": "org.apache.james.protocols.api.handler.CommandDispatcher",
    "message": "Error dispatching command for request TOP",
    "context": "default",
    "exception": "java.lang.ArrayIndexOutOfBoundsException: null\n"
}
```

This is a rare error though.

Let's investigate where this `ArrayIndexOutOfBoundsException` comes from.

**Comment by chibenwa** [comment]
Full log

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 356
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:79)
	at org.apache.james.protocols.pop3.core.POP3MessageCommandDelegate.lambda$getMetaData$2(POP3MessageCommandDelegate.java:77)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.apache.james.protocols.pop3.core.POP3MessageCommandDelegate.getMetaData(POP3MessageCommandDelegate.java:77)
	at org.apache.james.protocols.pop3.core.POP3MessageCommandDelegate.handleValidArgs(POP3MessageCommandDelegate.java:60)
	at org.apache.james.protocols.pop3.core.POP3MessageCommandDelegate.lambda$handleMessageRequest$0(POP3MessageCommandDelegate.java:49)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.apache.james.protocols.pop3.core.POP3MessageCommandDelegate.handleMessageRequest(POP3MessageCommandDelegate.java:49)
	at org.apache.james.protocols.pop3.core.TopCmdHandler.lambda$onCommand$0(TopCmdHandler.java:91)
	at org.apache.james.util.MDCBuilder.withMdc(MDCBuilder.java:44)
	at org.apache.james.protocols.pop3.core.TopCmdHandler.lambda$onCommand$1(TopCmdHandler.java:86)
	at org.apache.james.metrics.api.MetricFactory.decorateSupplierWithTimerMetric(MetricFactory.java:37)
	at org.apache.james.protocols.pop3.core.TopCmdHandler.onCommand(TopCmdHandler.java:85)
	at org.apache.james.protocols.pop3.core.TopCmdHandler.onCommand(TopCmdHandler.java:45)
	at org.apache.james.protocols.api.handler.CommandDispatcher.dispatchCommandHandlers(CommandDispatcher.java:165)
	at org.apache.james.protocols.api.handler.CommandDispatcher.onLine(CommandDispatcher.java:142)
	at org.apache.james.protocols.netty.BasicChannelInboundHandler.channelRead(BasicChannelInboundHandler.java:195)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by chibenwa** [comment]
How to reproduce?

```
# openssl s_client -connect 192.168.43.66:995
+OK <6d73e702.1734626295963@ges-tmail-01> POP3 server (JAMES POP3 Server ) ready 

USER paul.nationaladmin@govmu.org
+OK

PASS XXXXXX
+OK Welcome paul.nationaladmin@govmu.org

LIST
+OK 31 5265519
1 425728
2 4064
3 21438
4 88391
5 185278
6 506001
7 88157
8 567539
9 7508
10 8579
11 8501
12 1001
13 971
14 971
15 970
16 21847
17 121848
18 319729
19 21186
20 22389
21 152240
22 75751
23 442092
24 761095
25 23181
26 14265
27 91128
28 436229
29 640412
30 206246
31 784
.

TOP 1 0
+OK Message follows
Content-Type: multipart/mixed;
 boundary="-=Part.ac2.48e371c5c4acbfc6.193af1ff078.ad37d8ecfb2b9f47=-"

.
TOP 0 0
-ERR
```

The later triggers the error.

**Comment by chibenwa** [comment]
![Image](https://github.com/user-attachments/assets/58e493fa-d0aa-44c0-b0b6-75d0caee3eab)

![Image](https://github.com/user-attachments/assets/3508dc48-296d-453c-840c-62637f7cfb9c)

**Comment by chibenwa** [comment]
CF https://github.com/apache/james-project/pull/2575
