### ISSUE TITLE
[MU] Quota errors

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5378]
Should be less verbose

```
Caused by: jakarta.mail.MessagingException: Could not append due to quota error
	at org.apache.james.transport.mailets.delivery.MailboxAppenderImpl.lambda$append$7(MailboxAppenderImpl.java:127)
	at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3840)
	at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3930)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	... 62 common frames omitted
Caused by: org.apache.james.mailbox.exception.OverQuotaException: You use too much space in #private&akishtoo@govmu.org
	at org.apache.james.mailbox.store.quota.QuotaChecker.trySizeAddition(QuotaChecker.java:68)
	at org.apache.james.mailbox.store.quota.QuotaChecker.tryAddition(QuotaChecker.java:59)
	at org.apache.james.mailbox.store.StoreMessageManager.lambda$createAndDispatchMessage$5(StoreMessageManager.java:537)
	at com.github.fge.lambdas.consumers.ConsumerChainer.lambda$sneakyThrow$9(ConsumerChainer.java:73)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	... 54 common frames omitted
```

And likely not retried.

=> INFO

**Comment by chibenwa** [comment]
Very likely generated by a data race...

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2582

**Comment by quantranhong1999** [comment]
tmail: https://github.com/linagora/tmail-backend/pull/1431
