### ISSUE TITLE
Useless warning in logs when modifying a subfolder to a folder (which seems to work fine)

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#558]
- Have a folder "A" and a sub-folder "B" ("A/B")
- Modifying sub-folder "B" to modify its parent from "A" to "Unified Inbox"
- The Subfolder "A/B" is now a Folder "B"
but a useless warning is added in logs
```
esn_james       | 15:11:09.588 [WARN ] o.a.j.j.m.MailboxFactory - Cannot find mailbox for: A.B
esn_james       | org.apache.james.mailbox.exception.MailboxNotFoundException: null
esn_james       | 	at org.apache.james.mailbox.cassandra.mail.CassandraMailboxMapper.findMailboxByPath(CassandraMailboxMapper.java:89)
esn_james       | 	at org.apache.james.mailbox.store.StoreMailboxManager.getMailbox(StoreMailboxManager.java:460)
esn_james       | 	at org.apache.james.jmap.model.MailboxFactory.fromMailboxPath(MailboxFactory.java:54)
esn_james       | 	at org.apache.james.jmap.methods.GetMailboxesMethod.lambda$getMailboxesResponse$0(GetMailboxesMethod.java:95)
esn_james       | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
esn_james       | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
esn_james       | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
esn_james       | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
esn_james       | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
esn_james       | 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
esn_james       | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
esn_james       | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
esn_james       | 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
esn_james       | 	at org.apache.james.jmap.methods.GetMailboxesMethod.getMailboxesResponse(GetMailboxesMethod.java:100)
esn_james       | 	at org.apache.james.jmap.methods.GetMailboxesMethod.process(GetMailboxesMethod.java:79)
esn_james       | 	at org.apache.james.jmap.methods.RequestHandler.lambda$extractAndProcess$1(RequestHandler.java:67)
esn_james       | 	at java.util.Optional.map(Optional.java:215)
esn_james       | 	at org.apache.james.jmap.methods.RequestHandler.handle(RequestHandler.java:57)
esn_james       | 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
esn_james       | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
esn_james       | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
esn_james       | 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
esn_james       | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
esn_james       | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
esn_james       | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
esn_james       | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
esn_james       | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
esn_james       | 	at org.apache.james.jmap.JMAPServlet.doPost(JMAPServlet.java:71)
esn_james       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
esn_james       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
esn_james       | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
esn_james       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
esn_james       | 	at org.apache.james.jmap.FirstUserConnectionFilter.doFilter(FirstUserConnectionFilter.java:71)
esn_james       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
esn_james       | 	at org.apache.james.jmap.AuthenticationFilter.doFilter(AuthenticationFilter.java:75)
esn_james       | 	at org.apache.james.jmap.BypassAuthOnRequestMethod.tryAuth(BypassAuthOnRequestMethod.java:115)
esn_james       | 	at org.apache.james.jmap.BypassAuthOnRequestMethod.doFilter(BypassAuthOnRequestMethod.java:97)
esn_james       | 	at org.apache.james.jmap.AllowAllCrossOriginRequests.doFilter(AllowAllCrossOriginRequests.java:46)
esn_james       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
esn_james       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
esn_james       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
esn_james       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
esn_james       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
esn_james       | 	at org.eclipse.jetty.server.Server.handle(Server.java:517)
esn_james       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
esn_james       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
esn_james       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
esn_james       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
esn_james       | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
esn_james       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
esn_james       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
esn_james       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
esn_james       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
esn_james       | 	at java.lang.Thread.run(Thread.java:745)
```

Why such a warning if the move is working.

**Comment by chibenwa** [comment]
No longer happening?
