### ISSUE TITLE
ClosedChannelException is raised for emails that are unauthenticated and restricted

### ISSUE THREAD

**Issue by pleira** [linagora/james-project#609]
I am running a slightly modified James Server (SPFHandler). Sometimes, when processing the email, ClosedChannelException is raised for emails processed (unauthenticated and restricted):

```
DEBUG 05:42:27,051 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.smtp.core.esmtp.EhloCmdHandler: [250-1fire.pitagoral.com Hello 126.com [218.26.205.31]), 250-AUTH LOGIN PLAIN, 250-AUTH=LOGIN PLAIN, 250-PIPELINING, 250-ENHANCEDSTATUSCODES, 250-8BITMIME, 250 STARTTLS]
DEBUG 05:42:27,515 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: RSET
DEBUG 05:42:27,517 | james.smtpserver | Id='435381597' User='' Lookup command handler for command: RSET
DEBUG 05:42:27,517 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.smtp.core.RsetCmdHandler: org.apache.james.protocols.api.AbstractResponse$1@51386045
DEBUG 05:42:27,970 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: MAIL
DEBUG 05:42:27,971 | james.smtpserver | Id='435381597' User='' Lookup command handler for command: MAIL
DEBUG 05:42:27,972 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.smtpserver.fastfail.SPFHandler
INFO  05:42:27,972 | james.smtpserver | Id='435381597' User='' No Sender or HELO/EHLO present
DEBUG 05:42:27,972 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@7a2cfe18
DEBUG 05:42:27,972 | james.smtpserver | Id='435381597' User='' org.apache.james.smtpserver.fastfail.SPFHandler: result=8 (DECLINED)
DEBUG 05:42:27,972 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@780f72e1
DEBUG 05:42:27,972 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.smtpserver.fastfail.ValidSenderDomainHandler
DEBUG 05:42:27,976 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@7a2cfe18
DEBUG 05:42:27,976 | james.smtpserver | Id='435381597' User='' org.apache.james.smtpserver.fastfail.ValidSenderDomainHandler: result=8 (DECLINED)
DEBUG 05:42:27,976 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@780f72e1
DEBUG 05:42:27,977 | james.smtpserver | Id='435381597' User='' org.apache.james.smtpserver.JamesMailCmdHandler: [250 2.1.0 Sender <rtyrdudthfffxddh@126.com> OK]
DEBUG 05:42:28,453 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: RCPT
DEBUG 05:42:28,454 | james.smtpserver | Id='435381597' User='' Lookup command handler for command: RCPT
DEBUG 05:42:28,459 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.smtpserver.fastfail.DNSRBLHandler
INFO  05:42:28,604 | james.smtpserver | Id='435381597' User='' Connection from 218.26.205.31 restricted by zen.spamhaus.org. to SMTP AUTH/postmaster/abuse.
DEBUG 05:42:28,606 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@7a2cfe18
INFO  05:42:28,606 | james.smtpserver | Id='435381597' User='' org.apache.james.smtpserver.fastfail.DNSRBLHandler: result=2 (DENY)
DEBUG 05:42:28,606 | james.smtpserver | Id='435381597' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@780f72e1
DEBUG 05:42:28,606 | james.smtpserver | Id='435381597' User='' org.apache.james.smtpserver.JamesRcptCmdHandler: [554 5.7.1 Rejected: unauthenticated e-mail from /218.26.205.31 is restricted.  Contact the postmaster for details.]
DEBUG 05:42:29,084 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: QUIT
DEBUG 05:42:29,085 | james.smtpserver | Id='435381597' User='' Lookup command handler for command: QUIT
DEBUG 05:42:29,085 | james.smtpserver | Id='435381597' User='' org.apache.james.protocols.smtp.core.QuitCmdHandler: [221 2.0.0 1fire.pitagoral.com Service closing transmission channel]
INFO  05:42:29,085 | james.smtpserver | Id='435381597' User='' Connection closed for 218.26.205.31
INFO  05:42:29,085 | james.smtpserver | Id='435381597' User='' Connection closed for 218.26.205.31
DEBUG 05:42:29,087 | james.smtpserver | Id='435381597' User='' Unable to process request
java.nio.channels.ClosedChannelException
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:168)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:192)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:121)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.handler.execution.ExecutionHandler.handleDownstream(ExecutionHandler.java:176)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.write(Channels.java:704)
        at org.jboss.netty.channel.Channels.write(Channels.java:671)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348)
        at org.apache.james.protocols.netty.NettyProtocolTransport.writeToClient(NettyProtocolTransport.java:116)
        at org.apache.james.protocols.api.AbstractProtocolTransport.writeResponseToClient(AbstractProtocolTransport.java:150)
        at org.apache.james.protocols.api.AbstractProtocolTransport.writeResponse(AbstractProtocolTransport.java:67)
        at org.apache.james.protocols.netty.BasicChannelUpstreamHandler.messageReceived(BasicChannelUpstreamHandler.java:156)
        at org.apache.james.smtpserver.netty.SMTPChannelUpstreamHandler.messageReceived(SMTPChannelUpstreamHandler.java:61)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
DEBUG 05:42:29,088 | james.smtpserver | Id='435381597' User='' Unable to process request
java.nio.channels.ClosedChannelException
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:168)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:192)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:121)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.handler.execution.ExecutionHandler.handleDownstream(ExecutionHandler.java:176)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.write(Channels.java:704)
        at org.jboss.netty.channel.Channels.write(Channels.java:671)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348)
        at org.apache.james.protocols.netty.NettyProtocolTransport.close(NettyProtocolTransport.java:122)
        at org.apache.james.protocols.api.AbstractProtocolTransport.writeResponseToClient(AbstractProtocolTransport.java:159)
        at org.apache.james.protocols.api.AbstractProtocolTransport.writeResponse(AbstractProtocolTransport.java:67)
        at org.apache.james.protocols.netty.BasicChannelUpstreamHandler.messageReceived(BasicChannelUpstreamHandler.java:156)
        at org.apache.james.smtpserver.netty.SMTPChannelUpstreamHandler.messageReceived(SMTPChannelUpstreamHandler.java:61)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by chibenwa** [comment]
No longer happens
