### ISSUE TITLE
CommandInjectionDetectedException is raised by valid emails having "starttls" in their bodies

### ISSUE THREAD

**Issue by pleira** [linagora/james-project#668]
CommandInjectionDetectedException's is raised by valid emails having "starttls" in its body. It happens in those coming from james server development mailing list as often the code changes involve lines of code where the term starttls appears.  

My SMTP server is configured as:
```xml
    <smtpserver enabled="true">
        <jmxName>smtpserver-global</jmxName>
        <bind>0.0.0.0:25</bind>
        <connectionBacklog>20</connectionBacklog>
        <tls socketTLS="false" startTLS="false">
            <keystore>file://conf/keystore</keystore>
            <secret>********</secret>
            <provider>org.bouncycastle.jce.provider.BouncyCastleProvider</provider>
            <algorithm>SunX509</algorithm>
        </tls>
        <connectiontimeout>360</connectiontimeout>
        <connectionLimit>18</connectionLimit>
        <connectionLimitPerIP>5</connectionLimitPerIP>
        <authRequired>false</authRequired>
           <authorizedAddresses>127.0.0.0/8</authorizedAddresses>
        <verifyIdentity>true</verifyIdentity>
        <maxmessagesize>0</maxmessagesize>
           <addressBracketsEnforcement>true</addressBracketsEnforcement>
        <smtpGreeting>JAMES SMTP awesome Server</smtpGreeting>
        <handlerchain>
            <handler class="org.apache.james.smtpserver.fastfail.ValidRcptHandler"/>
            <handler class="org.apache.james.smtpserver.CoreCmdHandlerLoader"/>
        </handlerchain>
    </smtpserver>
    <smtpserver enabled="true">
        <jmxName>smtpserver-authenticated</jmxName>
        <bind>0.0.0.0:587</bind>
        <connectionBacklog>20</connectionBacklog>
        <tls socketTLS="false" startTLS="true">
            <keystore>file://conf/keystore</keystore>
            <secret>********</secret>
            <provider>org.bouncycastle.jce.provider.BouncyCastleProvider</provider>
            <algorithm>SunX509</algorithm>
        </tls>
        <connectiontimeout>360</connectiontimeout>
        <connectionLimit>18</connectionLimit>
        <connectionLimitPerIP>5</connectionLimitPerIP>
        <authRequired>true</authRequired>
        <authorizedAddresses>127.0.0.0/8</authorizedAddresses>
        <verifyIdentity>false</verifyIdentity>
        <maxmessagesize>0</maxmessagesize>
        <addressBracketsEnforcement>true</addressBracketsEnforcement>
        <smtpGreeting>JAMES SMTP Secured Server</smtpGreeting>
        <handlerchain>
            <handler class="org.apache.james.smtpserver.fastfail.ValidRcptHandler"/>
            <handler class="org.apache.james.smtpserver.CoreCmdHandlerLoader"/>
        </handlerchain>
    </smtpserver>
```
The log before the exception is as follows:
```text
INFO  2017-03-04 00:02:14,670 | james.smtpserver | Id='1686819552' User='' Connection established from 140.211.11.3
DEBUG 2017-03-04 00:02:14,833 | james.smtpserver | Id='1686819552' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: HELO
DEBUG 2017-03-04 00:02:14,833 | james.smtpserver | Id='1686819552' User='' Lookup command handler for command: HELO
DEBUG 2017-03-04 00:02:14,833 | james.smtpserver | Id='1686819552' User='' org.apache.james.protocols.smtp.core.HeloCmdHandler: [250 1fire.pitagoral.com Hello mail.apache.org [140.211.11.3])]
DEBUG 2017-03-04 00:02:14,995 | james.smtpserver | Id='1686819552' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: MAIL
DEBUG 2017-03-04 00:02:14,996 | james.smtpserver | Id='1686819552' User='' Lookup command handler for command: MAIL
DEBUG 2017-03-04 00:02:14,996 | james.smtpserver | Id='1686819552' User='' org.apache.james.smtpserver.JamesMailCmdHandler: [250 2.1.0 Sender <server-dev-return-61708-pablo.****=pitagoral.com@james.apache.org> OK]
DEBUG 2017-03-04 00:02:15,158 | james.smtpserver | Id='1686819552' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: RCPT
DEBUG 2017-03-04 00:02:15,158 | james.smtpserver | Id='1686819552' User='' Lookup command handler for command: RCPT
DEBUG 2017-03-04 00:02:15,158 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.fastfail.ValidRcptHandler
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@deee6c4
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' org.apache.james.smtpserver.fastfail.ValidRcptHandler: result=8 (DECLINED)
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@7ab3cd0d
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.AuthRequiredToRelayRcptHook
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@deee6c4
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' org.apache.james.smtpserver.AuthRequiredToRelayRcptHook: result=8 (DECLINED)
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@7ab3cd0d
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.SenderAuthIdentifyVerificationRcptHook
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@deee6c4
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' org.apache.james.smtpserver.SenderAuthIdentifyVerificationRcptHook: result=8 (DECLINED)
DEBUG 2017-03-04 00:02:15,160 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@7ab3cd0d
DEBUG 2017-03-04 00:02:15,161 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.protocols.smtp.core.PostmasterAbuseRcptHook
DEBUG 2017-03-04 00:02:15,161 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.protocols.smtp.core.log.HookResultLogger@deee6c4
DEBUG 2017-03-04 00:02:15,161 | james.smtpserver | Id='1686819552' User='' org.apache.james.protocols.smtp.core.PostmasterAbuseRcptHook: result=8 (DECLINED)
DEBUG 2017-03-04 00:02:15,161 | james.smtpserver | Id='1686819552' User='' executing hook org.apache.james.smtpserver.jmx.HookResultJMXMonitor@7ab3cd0d
DEBUG 2017-03-04 00:02:15,161 | james.smtpserver | Id='1686819552' User='' org.apache.james.smtpserver.JamesRcptCmdHandler: [250 2.1.5 Recipient <pablo.****@pitagoral.com> OK]
DEBUG 2017-03-04 00:02:15,323 | james.smtpserver | Id='1686819552' User='' org.apache.james.protocols.api.handler.CommandDispatcher received: DATA
DEBUG 2017-03-04 00:02:15,868 | james.smtpserver | Id='1686819552' User='' Lookup command handler for command: DATA
DEBUG 2017-03-04 00:02:15,868 | james.smtpserver | Id='1686819552' User='' org.apache.james.smtpserver.JamesDataCmdHandler: [354 Ok Send data ending with <CRLF>.<CRLF>]
DEBUG 2017-03-04 00:02:16,035 | james.smtpserver | Id='1686819552' User='' Unable to process request
org.apache.james.protocols.smtp.CommandInjectionDetectedException
        at org.apache.james.protocols.smtp.AllButStartTlsDelimiterChannelHandler.decode(AllButStartTlsDelimiterChannelHandler.java:40)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
......
```

**Comment by chibenwa** [comment]
Thanks for report.

I belive we should treat it ASAP

**Comment by chibenwa** [comment]
Hi,

https://github.com/linagora/james-project/pull/671 should solve the issue : 

 - Enable command injection detection only on commands (and not on data)
 - Make the command injection detection more clever.

Cheers,

Benoit
